version: '2'
services:
  pgadmin4:
    image: dpage/pgadmin4
    networks:
      - pgrst-dev_network
    ports:
      - "5003:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=email
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./conf/servers.json:/pgadmin4/servers.json
      - ./conf/config_local.py:/pgadmin4/config_local.py

networks:
  pgrst-dev_network:
    external: true
