version: '2'
services:
  postgrest-watch:
    image: fpco/stack-build
    user: ${HOST_UID}:${HOST_GID}
    working_dir: /home/pgrst-user/postgrest
    entrypoint: /bin/bash
    # entrypoint: stack build --file-watch
    stdin_open: true
    tty: true
    networks:
      - pgrst-dev_network
    volumes:
      - pgrst-dev_passwd:/etc/
      - ../../base/postgrest:/home/pgrst-user/postgrest
      - ../../base/.stack:/home/pgrst-user/.stack
      - ../../base/.stack-work:/home/pgrst-user/postgrest/.stack-work

networks:
  pgrst-dev_network:
    external: true


volumes:
  pgrst-dev_passwd:
    external: true
