version: '2'

services:
  swagger:
    image: swaggerapi/swagger-ui:latest
    networks:
      - pgrst-dev_network
    ports:
      - "5004:8080"
    environment:
      - API_URL=http://localhost:5001/

networks:
  pgrst-dev_network:
    external: true
