version: '2'
services:
  postgres:
    image: postgres:latest
    command: postgres -c log_statement=all
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=superuserpass
      - POSTGRES_DB=dbname

    networks:
      - network

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  postgrest:
    build:
      context: .
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    tty: true
    stdin_open: true
    networks:
      - network
    volumes:
      - passwd:/etc/
      - stack:/home/pgrst-user/.stack
      - stack-work:/home/pgrst-user/postgrest/.stack-work
      - ./postgrest:/home/pgrst-user/postgrest
      - ./postgrest.conf:/etc/postgrest.conf

  mitmproxy:
    image: mitmproxy/mitmproxy
    networks:
      - network
    entrypoint: mitmdump
    command: -s /root/middleware.py --mode="reverse:http://postgrest:3000" 
    ports:
      - "5001:8080"
    volumes:
      - ./middleware.py:/root/middleware.py

networks:
  network:
    driver: bridge

volumes:
  passwd:
  stack:
  stack-work:
