version: '2'
services:
  build-watch:
    image: fpco/stack-build
    user: ${HOST_UID}:${HOST_GID}
    working_dir: /home/pgrst-user/postgrest
    entrypoint: stack build --file-watch
    stdin_open: true
    tty: true
    networks:
      - pgrst-dev_network
    volumes:
      - pgrst-dev_passwd:/etc/
      - pgrst-dev_stack:/home/pgrst-user/.stack
      - pgrst-dev_stack-work:/home/pgrst-user/postgrest/.stack-work
      - ../../base/postgrest:/home/pgrst-user/postgrest

networks:
  pgrst-dev_network:
    external: true


volumes:
  pgrst-dev_passwd:
    external: true
  pgrst-dev_stack:
    external: true
  pgrst-dev_stack-work:
    external: true
